# Build base image: docker build -t pipeline/base docker/base/
# Build this image: docker build -t pipeline/pgv docker/pgv/

FROM pipeline/base

######## Open questions
# how do we deal with installing the netMHC suite?
# how do we deal with installing Google Cloud SDK? Do we want that as part of the pipeline?
