# Copyright (c) 2018. Mount Sinai School of Medicine
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
    "reference.rules"

# This file exists only to prepare the reference data.

rule all:
  input:
    rules.star_align_reference.output,
    rules.bwa_index_reference.output,
    rules.samtools_index_reference.output,
    rules.extract_contig_names.output,
    rules.picard_sequence_dict_reference.output
