"""
To see how Snakemake behaves with certain commands given the current config.json, 
try these examples:

Print jobs (and their shell commands) required to produce an aligned tumor DNA file:
snakemake -np /data/smoking-sigs/5/workdir/5T_aligned.sam --cores=24

Print jobs (and their shell commands) required to produce the MuTect2 output:
snakemake -np /data/smoking-sigs/5/workdir/5_mutect2.vcf --cores=24

Note that these commands need to be run from this directory. Also, this file assumes the 
existence of a config.json in the same directory with data of the form:

{
    "homedir": "path/to/homedir",
    "input": {
        "id": "some-id",
        "normal": "path/to/normal.bam",
        "tumor": "path/to/tumor.bam"
    },
    "reference": {
        "genome": "path/to/genome.fasta",
        "dbsnp": "path/to/dbsnp.vcf"
    }
}

The files listed in this config have to exist.

"""

import os

configfile: "config.json"

include:
    "gatk.rules"
include:
    "alignment.rules"

HOMEDIR = config["homedir"]
SAMPLE_ID = config["input"]["id"]

# DNA processing: MuTect2 variant calling

rule all:
  input:
    os.path.join(HOMEDIR, SAMPLE_ID, "workdir", SAMPLE_ID + "_mutect2.vcf")

rule copy_normal_bam:
  input:
    config["input"]["normal"]
  output:
    os.path.join(HOMEDIR, SAMPLE_ID, "workdir", SAMPLE_ID + "N.bam")
  shell:
    "cp {input} {output}"

rule copy_tumor_bam:
  input:
    config["input"]["tumor"]
  output:
    os.path.join(HOMEDIR, SAMPLE_ID, "workdir", SAMPLE_ID + "T.bam")
  shell:
    "cp {input} {output}"

rule sort_bam_by_read_name:
  input:
    "{prefix}.bam"
  output:
    "{prefix}_read_name_sorted.bam"
  threads: 12
  params:
    tmpdir="{prefix}_tmp"
  benchmark:
    "{prefix}_sort_bam_by_read_name_benchmark.txt"
  shell:
    "sambamba sort -N -t {threads} --tmpdir={params.tmpdir} -o {output} -p {input}"

rule convert_bam_to_fastq:
  input:
    "{prefix}_read_name_sorted.bam"
  output:
    "{prefix}_read_name_sorted.fastq"
  benchmark:
    "{prefix}_convert_bam_to_fastq_benchmark.txt"
  shell:
    "samtools bam2fq {input} > {output}"

rule mutect2:
  input:
    normal = "{prefix}N_aligned_coordinate_sorted_dups_indelreal_bqsr.bam",
    tumor = "{prefix}T_aligned_coordinate_sorted_dups_indelreal_bqsr.bam"
  output:
    "{prefix}_mutect2.vcf"
  params:
    reference = config["reference"]["genome"],
    dbsnp = config["reference"]["dbsnp"]
  benchmark:
    "{prefix}_mutect2_benchmark.txt"
  log:
    "{prefix}_mutect2.log"
  shell:
    "gatk -Xmx20g "
    "-T MuTect2 -I:normal {input.normal} -I:tumor {input.tumor} -R {params.reference} "
    "--dbsnp {params.dbsnp} -o {output} "
    "2> {log}"

# RNA processing

# STAR alignment

# markdups